<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>mxddsgen_ament_shim</name>
  <version>0.0.0</version>
  <description>Ament shim for Micro-XRCE-DDS-Gen</description>
  <maintainer email="seantfish@gmail.com">Sean Fish</maintainer>
  <license>GPL-3.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <build_depend>micro-xrce-dds-gen</build_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
